version: '3.5'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:password@db:5432/blog
      CONFIG_NAME: DevConfig
    volumes:
      - ./blog:/app/blog
    command: bash -c "flask db upgrade && python3 wsgi.py"
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blog -U user" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

