"""empty message

Revision ID: 2048deabf62e
Revises: 8fa30636fa6b
Create Date: 2023-04-26 15:03:39.752701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2048deabf62e'
down_revision = '8fa30636fa6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.String(length=200), server_default='', nullable=False))
    op.add_column('articles', sa.Column('body', sa.Text(), server_default='', nullable=False))
    op.add_column('articles', sa.Column('dt_created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('articles', sa.Column('dt_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'dt_updated')
    op.drop_column('articles', 'dt_created')
    op.drop_column('articles', 'body')
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###
