"""empty message

Revision ID: 338d92b0223d
Revises: 500f23b4eaa2
Create Date: 2023-04-24 12:33:54.292658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338d92b0223d'
down_revision = '500f23b4eaa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
